--
-- PostgreSQL database dump
--

-- Dumped from database version 14.6 (Homebrew)
-- Dumped by pg_dump version 14.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: gendertype; Type: TYPE; Schema: public; Owner: marinas
--

CREATE TYPE public.gendertype AS ENUM (
    'male',
    'female'
);


ALTER TYPE public.gendertype OWNER TO marinas;

--
-- Name: statustype; Type: TYPE; Schema: public; Owner: marinas
--

CREATE TYPE public.statustype AS ENUM (
    'accept',
    'reject',
    'in_process'
);


ALTER TYPE public.statustype OWNER TO marinas;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Actors; Type: TABLE; Schema: public; Owner: marinas
--

CREATE TABLE public."Actors" (
    id integer NOT NULL,
    first_name character varying(120) NOT NULL,
    last_name character varying(120) NOT NULL,
    age integer NOT NULL,
    gender public.gendertype NOT NULL,
    email character varying NOT NULL,
    phone character varying(120) NOT NULL,
    photo_link character varying(500) NOT NULL,
    seeking_movie boolean NOT NULL,
    CONSTRAINT check_valid_age CHECK ((age > 0))
);


ALTER TABLE public."Actors" OWNER TO marinas;

--
-- Name: Actors_id_seq; Type: SEQUENCE; Schema: public; Owner: marinas
--

CREATE SEQUENCE public."Actors_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Actors_id_seq" OWNER TO marinas;

--
-- Name: Actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marinas
--

ALTER SEQUENCE public."Actors_id_seq" OWNED BY public."Actors".id;


--
-- Name: Casting; Type: TABLE; Schema: public; Owner: marinas
--

CREATE TABLE public."Casting" (
    id integer NOT NULL,
    actor_id integer,
    movie_id integer,
    role character varying(120) NOT NULL,
    casting_date timestamp without time zone,
    casting_address character varying(250) NOT NULL,
    status public.statustype NOT NULL
);


ALTER TABLE public."Casting" OWNER TO marinas;

--
-- Name: Casting_id_seq; Type: SEQUENCE; Schema: public; Owner: marinas
--

CREATE SEQUENCE public."Casting_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Casting_id_seq" OWNER TO marinas;

--
-- Name: Casting_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marinas
--

ALTER SEQUENCE public."Casting_id_seq" OWNED BY public."Casting".id;


--
-- Name: Movies; Type: TABLE; Schema: public; Owner: marinas
--

CREATE TABLE public."Movies" (
    id integer NOT NULL,
    title character varying NOT NULL,
    genres character varying[] NOT NULL,
    release_date timestamp without time zone,
    seeking_actor boolean NOT NULL
);


ALTER TABLE public."Movies" OWNER TO marinas;

--
-- Name: Movies_id_seq; Type: SEQUENCE; Schema: public; Owner: marinas
--

CREATE SEQUENCE public."Movies_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Movies_id_seq" OWNER TO marinas;

--
-- Name: Movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marinas
--

ALTER SEQUENCE public."Movies_id_seq" OWNED BY public."Movies".id;


--
-- Name: Actors id; Type: DEFAULT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Actors" ALTER COLUMN id SET DEFAULT nextval('public."Actors_id_seq"'::regclass);


--
-- Name: Casting id; Type: DEFAULT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Casting" ALTER COLUMN id SET DEFAULT nextval('public."Casting_id_seq"'::regclass);


--
-- Name: Movies id; Type: DEFAULT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Movies" ALTER COLUMN id SET DEFAULT nextval('public."Movies_id_seq"'::regclass);


--
-- Data for Name: Actors; Type: TABLE DATA; Schema: public; Owner: marinas
--

COPY public."Actors" (id, first_name, last_name, age, gender, email, phone, photo_link, seeking_movie) FROM stdin;
3	John	Holms	32	male	johnholms@gnmail.com	1234567892	https://images.unsplash.com/photo-1542583701-20d3be307eba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=770&q=80	t
4	Kyle	Locman	29	male	kylelocman@gmail.com	1234567899	https://images.unsplash.com/photo-1587715718640-987708ba38e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80	f
5	Kyle 2	Locman 2	29	male	kylelocman2@gmail.com	2234567899	https://images.unsplash.com/photo-1587715718640-987708ba38e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80	f
\.


--
-- Data for Name: Casting; Type: TABLE DATA; Schema: public; Owner: marinas
--

COPY public."Casting" (id, actor_id, movie_id, role, casting_date, casting_address, status) FROM stdin;
3	3	2	second	2023-10-01 15:00:00	123 DHfghjkd street, New York, NY, 12345	in_process
\.


--
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: marinas
--

COPY public."Movies" (id, title, genres, release_date, seeking_actor) FROM stdin;
2	Smile	{Comedy}	2023-12-12 00:00:00	t
3	Cry cry cry	{Drama}	2024-12-12 00:00:00	t
4	Run run run	{Sport,Documental}	2024-12-12 00:00:00	t
\.


--
-- Name: Actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marinas
--

SELECT pg_catalog.setval('public."Actors_id_seq"', 5, true);


--
-- Name: Casting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marinas
--

SELECT pg_catalog.setval('public."Casting_id_seq"', 3, true);


--
-- Name: Movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marinas
--

SELECT pg_catalog.setval('public."Movies_id_seq"', 4, true);


--
-- Name: Actors Actors_email_key; Type: CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Actors"
    ADD CONSTRAINT "Actors_email_key" UNIQUE (email);


--
-- Name: Actors Actors_phone_key; Type: CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Actors"
    ADD CONSTRAINT "Actors_phone_key" UNIQUE (phone);


--
-- Name: Actors Actors_pkey; Type: CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Actors"
    ADD CONSTRAINT "Actors_pkey" PRIMARY KEY (id);


--
-- Name: Casting Casting_pkey; Type: CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Casting"
    ADD CONSTRAINT "Casting_pkey" PRIMARY KEY (id);


--
-- Name: Movies Movies_pkey; Type: CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "Movies_pkey" PRIMARY KEY (id);


--
-- Name: Casting Casting_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Casting"
    ADD CONSTRAINT "Casting_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public."Actors"(id) ON DELETE CASCADE;


--
-- Name: Casting Casting_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: marinas
--

ALTER TABLE ONLY public."Casting"
    ADD CONSTRAINT "Casting_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES public."Movies"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

