"""empty message

Revision ID: d8c98a4cae5e
Revises: 
Create Date: 2022-12-10 16:50:37.724591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c98a4cae5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gendertype'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('photo_link', sa.String(length=500), nullable=False),
    sa.Column('seeking_movie', sa.Boolean(), nullable=False),
    sa.CheckConstraint('age > 0', name='check_valid_age'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('seeking_actor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Casting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('casting_date', sa.DateTime(), nullable=True),
    sa.Column('casting_address', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('accept', 'reject', 'in_process', name='statustype'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Casting')
    op.drop_table('Movies')
    op.drop_table('Actors')
    # ### end Alembic commands ###
